//
//  TermsCondition.swift
//  Zepto
//
//  Created by Celestial on 11/02/25.
//

import SwiftUI

struct TermsOfUseView: View {
    @Environment(\.presentationMode) var presentationMode
    var body: some View {
        NavigationView{
            ScrollView {
                VStack(alignment: .leading, spacing: 12) {
                    
                    Text("Zepto Terms Of Use")
                        .font(.title)
                        .bold()
                        .underline()
                        .foregroundColor(.white)
                    
                    
                    Text("Version 1.0")
                        .italic()
                        .bold()
                        .foregroundColor(.white)
                    

                    Text("""
                This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                """)
                    .foregroundColor(.white)
                    
                    
                    Text("1. Terms of Use")
                        .bold()
                        .foregroundColor(.white)
                    
                    Text("""
                         1.1. The website www.zeptonow.com (“Website”) and mobile application ‘Zepto’ (App) (Website and App collectively referred to as the “Platform”) is owned, operated and managed by the Zepto Marketplace Private Limited, a private limited company incorporated in accordance with the provisions of the Indian Companies Act, 2013 and having its registered office situated at Ground Floor, Sy. No.32/5, BBMP Khata No. 224/215, Rupena Agrahara, Hosur Rd, Bommanahalli, Bengaluru, Karnataka, India, 560068.

                         1.2. These terms of use (“Terms”) govern your use of the Platform, and for the purpose of these Terms, Zepto Marketplace Private Limited including its subsidiaries, its holding company, its affiliates may wherever context so require, be also referred to as, “Zepto”, "We",  "Us", or "Our" and the terms “You”, “Your” or “User” refer to user of the Platform. We value the trust You have placed in Us and hence We maintain reasonable security standards for securing the transactions and Your information.

                         1.3. Please read these Terms carefully before You use the Platform. If You do not agree to these Terms, You may not use the services on the Platform, and We request You to uninstall the App and not access the Platform. By even merely using/accessing the Platform, You shall be contracting with Zepto and You signify Your acceptance to these Terms and other Zepto policies (including but not limited to the cancellation & refund Terms and published privacy policy (‘‘Privacy Notice’’) as posted on the Platform and amended from time to time, which takes effect on the date on which You use the Platform and thereby create a legally binding agreement to abide by the same. Further, by furnishing Your personal information, You consent to Zepto accessing Your personal information for the purpose of enabling transactions, You also agree that You are interested in availing the services through the Platform in accordance with these Terms.

                         1.4. Zepto retains an unconditional right to modify or amend these Terms. You can determine when these Terms were last modified by referring to the ‘Last Updated’ legend above. You can access the latest version of these Terms at any given time on the Platform. You should regularly review the Terms on the Platform. Zepto reserves the right to amend, suspend, discontinue or add any or all services without prior notice and can add or remove relevant terms and conditions, if necessary. Any updation of the Terms as a consequence of change in legal and regulatory compliances, shall be made in compliance thereof. Your continued use of and access to the Platform shall be Your consent to any changes made by Us in these Terms. In the event, the modified Terms are not acceptable to You, You should discontinue accessing the Platform.

                         2. Access to services

                         2.1. Zepto enables transactions on the Platform between participating sellers and service providers (“Seller(s)”) and Users. Users can order Products (defined hereunder) and services offered for sale by these Sellers in select serviceable areas across India. Zepto is not and cannot be a party to or control in any manner any transaction between the Platform's Users and Sellers.

                         2.2. You acknowledge that the Platform allows You to avail  a personal, limited, non-exclusive, non- transferable, and revocable privilege to access and use the Platform for the purposes of purchasing consumer goods such as grocery, apparel, electronics, health and wellness, café products including prepared foods and beverages (Café orders), Pet care etc (collectively, “Product(s)”) from the Sellers. The Services such as handling of Products, last mile delivery services including late night delivery and other services are provided with purchase of Products only at a fee as may be charged additionally.

                         2.3. The aforesaid revocable privilege to access does not include/permit resale or commercial use of the Platform or its Content (as defined below), in any manner. The Sellers may, at their discretion, add, modify or remove any of the Products and services listed above from time to time without notice. The Sellers and/or Zepto may also make applicable, at its discretion, additional terms and conditions specific to any category or section of Products or services in addition to these Terms and Your purchase of any of such category or section of Products or services shall also be governed by such additional terms and conditions. Zepto reserves the right to provide the services in any area or city in India, as may be determined by Zepto in its sole discretion. Before applying or registering for availing any of the services, We request You to please check if the services are available in Your area or city. Last mile delivery is provided by engaging third-party delivery service providers.

                         2.4. Zepto does not: (i) adopt any ‘unfair trade practices’ either on the Platform or otherwise with respect to its services; (ii) discriminate between Users of the same class or make any arbitrary classification of the Users and (iii) discriminate between the third-party delivery service providers.

                         2.5. Zepto functions solely as an online marketplace and acts as a facilitator enabling transactions between Users and Sellers on the Platform. At no point does Zepto take possession of any Products offered by Sellers nor does it hold any rights, title or interest in those Products and services. Zepto is not liable for any obligations related to non performance or breach of contracts between Users and Sellers as that is a bilateral arrangement between You and Seller. Furthermore, Zepto is neither responsible for poor or delayed Product or service performance nor for issues arising from Products that are out of stock, unavailable or back-ordered.

                         3. Eligibility to Use

                         3.1. The Products and services are not available to minors i.e., persons under the age of 18 (eighteen) years, undischarged insolvent, any Users who are not competent to enter into a contract under the Indian Contract Act, 1872, unless otherwise provided hereunder or to anyone previously suspended or removed by Zepto from availing the Products or services or accessing the Platform. You hereby represent that You are: (i) of legal age to form a binding contract, (ii) not a person barred from receiving the services from the Platform under the applicable laws;  (iii) competent to enter into a binding contract and (iv) have not been previously suspended or removed or disqualified for any reason from the Platform. If You are under the age of 18, You shall use and access the Platform only with the express consent of a parent or guardian and under their supervision.

                         3.2. You will not discriminate against third-party delivery service providers based on race, religion, caste, creed, national origin, disability, sexual orientation, sex, marital status, gender identity, age or any other metric which is deemed to be immoral and unlawful. Any credible proof of such discrimination, including any refusal to receive the Products or services based on the above metrics, whether alone or in conjunction with any other metric, shall render You ineligible, leading to suspension of access to the Platform. You will not have any claim, and We will not have any liability towards any such suspension.

                         3.3. You shall not make negative, defamatory, misleading, deceptive, or libelous remark about Us or Our brand, including Zepto and its agnates and cognates, on the Platform or otherwise, or take any actions that could harm Zepto's reputation or dilute its trademarks. Additionally, You will not impose an excessive load on the Platform's infrastructure or Our systems and networks.

                         4. User Account, Password and Security

                         4.1. In order to access the services of the Platform, You will have to register and create an account on the Platform by providing details as may be required (“Account”). When You use the Platform, Zepto may collect personal information such as Your name, email, age, photograph, address, mobile number, and contact details and also documents pertaining to the same. This includes demographic information like gender, occupation, and education, as well as Your activity on the Platform such as visited pages, clicked links, and transaction details, including financial information needed to provide services and manage the Platform effectively.

                         4.2. You are solely responsible for the information You provide to Us. You shall ensure and confirm that the Account information and all information provided by You is complete, accurate and up- to-date. If there is any change in the Account information, or if any information is found to be incomplete or incorrect, You shall promptly update Your Account information on the Platform or request Zepto for information revision or update. If the information provided by You is untrue, inaccurate, unauthorised, not current, or incomplete (or becomes untrue, inaccurate, not current, or incomplete),  Zepto reserves the right to refuse any and all the services, if Zepto has reasonable grounds to suspect that such information is untrue, inaccurate, not current, or incomplete. Zepto reserves the right to refuse access to the Platform at any time without notice.

                         4.3. Confidentiality of the Account credentials shall be Your responsibility. Zepto disclaims any liability for losses due to unauthorised access of Your account.

                         5. Payment related Information

                         5.1. The information related to the accepted payment methods on the Platform shall be displayed during the purchasing process.

                         5.2. To the extent permitted by applicable law and subject to the Privacy Notice, You acknowledge and agree that Zepto may use certain third-party vendors and service providers, including payment gateways, to process payments and manage payment card information. Such Parties are separate to Zepto and You will be subject to their terms and conditions while making any payment for the Products and services.

                         5.3. You undertake to provide valid bank details or other details required for facilitating payment towards the  transaction  (“Payment   Details”). By providing the Payment Details, You represent, warrant, and covenant that: (a) You are legally authorized to provide such Payment Details; (b) You are legally authorized to make payments using such Payment Details; and (c) such action does not violate the terms and conditions applicable to Your use of such Payment Details or applicable law. You may add, delete, and edit the Payment Details You have provided from time to time through the Platform.

                         5.4. Except to the extent otherwise required by applicable law, Zepto is not liable for any payments authorized through the Platform using Your Payment Details. Zepto is not liable for any payments that do not complete a transaction due to reasons including but not limited to following:
                         (a) Insufficient funds in Your bank account ;
                         (b) You have not provided correct Payment Details ;
                         (c) Technical issues or interruptions in the Platform or payment processing systems.
                         (d) Violation of any terms or conditions governing the use of Your Payment Details.
                         (e) Fraudulent activity or unauthorized use of Your Payment Details.
                         (f) Your payment card has expired;
                         (g) Any other reason for declining of payment transaction or
                         (h) Any other circumstances beyond Zepto’s reasonable control which prevent the execution of the transaction.

                         5.5. Zepto shall not be responsible or obligated to refund any money to You for any unauthorised transactions conducted on the Platform using Your Payment Details.
                         ‍‍
                         5.6. Gift Cards: You can use Zepto Gift Cards for the purchases on the Platform, by redeeming the value contained in such Gift Cards at the time of payment for the purchase of eligible Products or services only on the Platform. Gift Cards are subject to additional terms and conditions pertaining to their use and redemption and You agree and consent to abide by the same.

                         5.7. The payment facility facilitated by Zepto is neither a banking nor a financial service but is merely a facility providing an electronic, automated online electronic payment system, and receiving payment on delivery for the transactions on the Platform using the existing authorized banking infrastructure and card payment gateway networks, as may be applicable. For some payment methods, Your payment service provider may charge You certain fees, such as transaction fees or other fees, relating to the processing of Your transaction.

                         5.8. Title of any Products purchased by You on the Platform shall be transferred to You post You making applicable payment for the same and also comply with any requirements which areapplicable for the order

                         6. Price of Products and services

                         6.1. The prices for Products and services listed by Sellers on the Platform are determined entirely by the Sellers themselves and Zepto does not participate in or influence this pricing process in any manner. The prices of each of the Products and services may vary due to various factors and You may check the price on the Platform before placing an order. By placing an order You agree to pay the prices mentioned therein. All the Products listed on the Platform will be sold at Indian Rupees either at Maximum Retail Price (MRP) (inclusive of all taxes) or at a discounted price unless otherwise specified. The prices of the Products and services are an offer for sale by the Sellers and may be modified by the Sellers from time to time without any prior notice. Zepto endeavour to display the Products and services at the accurate prices as possible on the Platform. There may be inadvertent errors with respect to the price and other information of the Products or services that You may bring to Our notice of such errors and We shall effect necessary corrections, however Zepto shall not be liable in case Seller proceeds with canceling of such order.

                         6.2. The Users will be informed about all the charges, fees, and costs (including delivery fee) that may be levied on the purchase of the Products or services on the Platform at the checkout page during a transaction.

                         6.3. The expression like 'Lowest Prices' pertains to the computation of average prices for all Productsand services offered for sale by the Sellers on the Platform (in comparison to competitors in thequick commerce segment for groceries, in most of the cases) and are subject to availability ofstocks. Zepto   expressly disclaims any liability associated with the individual Products orservices sold on the Platform by the Sellers.

                         6.4. Promotional Vouchers: Promotional vouchers are issued under various nomenclatures such as Free Cash etc which are intended for instant use during a session or otherwise and shall lapse or expire unless used and are subject to revocation without any prior notice. 

                         7. Delivery fees, ETA and other charges

                         7.1. The delivery fees cover the delivery services as part of the sale of Products purchased by You on the Platform. The delivery of the order will be provided within the time period communicated to You through the Platform. While efforts are made to display an estimated time of arrival (ETA) for every order, the delivery time may vary due to factors such as third-party delivery service availability, demand, traffic, weather conditions, force majeure events, and other unforeseen circumstances. Although Zepto endeavors to deliver orders within a 10-minute ETA, the actual delivery time may exceed this estimate due to the aforementioned factors. You can view the ETA on the homepage of the Platform even before placing an order, ensuring You are informed about the ETA before proceeding. Orders placed by You may be split into multiple sub-orders, each potentially having a different ETA.

                         7.2. Additionally, You agree that certain charges, such as fees for rain, peak hours, high demand or surge periods, late-night delivery, packaging and handling, convenience or platform usage, small cart fees, or other applicable charges, may apply. These charges will be displayed in the "View Bill" section before the checkout page on the Platform.  Your order may have following components and corresponding documents:

                         7.2.1. Supply of Products and services by Sellers - Tax Invoice issued on behalf of the Sellers;

                         7.2.2. Supply of services, if any, by Zepto - Tax Invoice issued by Zepto.

                         7.3. The delivery of the orders will be made to the address specified by You at the time of placing theorder on the Platform. It is Your sole responsibility to ensure that the delivery address iscomplete, accurate and includes any additional instructions required to facilitate delivery. Zeptoand its Sellers shall not be liable for non-delivery or delays in delivery arising from an incorrector incomplete address provided by You.

                         7.4. The Products will ordinarily be delivered when an appropriate person is available to receive the order at the address provided by You. If You request that the delivery be left unattended at Your address, You expressly waive and release Zepto from any liability arising from the Products being left unattended, including, but not limited to, theft, tampering, contamination, or spoilage for any reasons including due to changes in temperature for items requiring chilled or frozen storage.

                         7.5. In the event You opt for ‘Cash on Delivery (CoD)’ mode, Seller/ third-party delivery service providers shall have the right to refuse delivery of the order to You if You fail to make the complete payment and Zepto shall treat such order as canceled order and shall not be liable for any losses or damage that may arise on account of such non delivery to You. You agree to pay the delivery fee or any other fees for such canceled order towards the cost incurred on such delivery attempt.

                         7.6. Alcoholic Beverage and Tobacco Products:

                         7.6.1. The delivery of alcoholic beverage and tobacco Products to You is subject to the fulfillment of eligibility criteria prescribed under the applicable law in this regard, which may vary from State to State. Zepto and/or Sellers may request You to provide Your identification and age proof documents to evidence compliance with the aforesaid, including permanent account number (PAN) card or other documents or such other information, as may be required under the law at the time of ordering and delivery of alcoholic beverage and tobacco Products. Notwithstanding anything contained in these Terms, the ordered alcoholic beverage and tobacco Products shall be delivered only to the person from whose account the order has been placed subject to verification at the time of delivery. You may be denied the delivery of the ordered Products in case of noncompliance with this requirement.

                         7.6.2. By accessing the alcoholic beverage and tobacco Products category on the Platform, You represent that You (i) comply with all the eligibility criteria under applicable law including legal age in Your state of domicile and/ or where You are accessing the Platform and/or placing the order, (ii) have not been previously suspended or prohibited from accessing or otherwise availing the services from the Platform; (iii) possess necessary permits, if applicable; and (iv) order for Your personal consumption only and not for resale.

                         7.6.3. Important User declaration: You agree and undertake to not provide the address of any public place, including but not limited to, educational institution, hospital, and religious places as Your delivery address for the order relating to alcoholic beverage and tobacco Products. You further agree and undertake that You do not fall under any of the below-mentioned conditions, whenever You are placing an order on the Platform:-
                         a. in drunken condition;
                         b. taking part in any unlawful activity;
                         c. driving any motor vehicle;
                         d. uniformed official, and on duty;  
                         e. below the legal age to consume alcoholic beverages and/or tobacco Products.

                         7.6.4. The delivery of such Products to You are subject to the right to refuse in case of any non compliance on Your part, of the above conditions.

                         7.7. Terms and Conditions for Purchase of Pharmaceutical Products and Telemedicine Consultations:

                         7.7.1. Zepto’s Role and Disclaimer of Liability
                         Zepto operates solely as a digital marketplace Platform connecting Users with third- party Seller(s) ("Pharmacy") for the sale and purchase of drugs and pharmaceutical Products which shall include but shall not be limited to medical devices, Prescription Drugs (as defined below) and other healthcare and wellness products (Pharmaceutical Products). Zepto expressly disclaims all liability for any omissions, errors, or actions conducted by the Pharmacy who are solely responsible for the verification and dispensing of Pharmaceutical Products. Zepto assumes no liability for the quality, accuracy, or efficacy of Pharmaceutical Products dispensed by the Pharmacy. Users acknowledge that the role of Zepto is restricted to facilitating communication and transactions between Users and Pharmacy, and that any order or transaction is governed solely between the User and the Pharmacy. It is hereby clarified that that the manufacturers themselves are responsible for all compliances relating to the manufacturing of the Pharmaceutical Products including any labelling, mandatory declaration requirements, etc. under the applicable law including but not limited to the Legal Metrology Act, 2009, Drugs & Cosmetics Act 1940, Drugs Rules 1945, Medical Devices Rules 2017, Cosmetics Rules 2020, the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954, Food Safety and Standards Act, 2006, Pharmacy Act,1948, Narcotics & Psychotropic Act 1985 rules and regulations, guidelines if any framed thereunder in each of the aforesaid laws. The Pharmacy shall comply with the requirement of all the applicable laws. In no event shall Zepto be liable for any non compliance on the part of manufacturers or Pharmacy. Similarly Zepto is not responsible if Pharmacy dispenses with wrong Pharmaceutical Products or expired Pharmaceutical Products to the Users.

                         7.7.2. Invitation to offer for sale
                         ‍‍Notwithstanding anything contained elsewhere in these Terms, the listing of Pharmaceutical Products on the Platform by the Pharmacy is merely an invitation to offer and not an offer for sale. When You place an order, it constitutes Your offer to enter into an agreement with the Pharmacy. The acceptance of Your offer will be determined by the respective Pharmacy after validation/verification of Your prescription (for Prescription Drugs) & ascertainment of stock availability in the Pharmacy (for all Pharmaceutical Products).

                         7.7.3 Prescription Requirements
                         ‍‍Users may purchase certain Pharmaceutical Products, herein referred to as "Prescription Drugs" provided they submit a prescription. These Prescription Drugs are offered for sale by Pharmacy through the Platform. The prescription must be uploaded on the Platform where it will be transmitted to the Pharmacy for validation/verification. Invoices will be issued in the name appearing on the prescription by the Pharmacy. If any discrepancies are observed in the prescription, Pharmacy reserves the right to cancel the order immediately. Pharmacy retains the right to reject any prescription order if discrepancies or inaccuracies are identified. Users may be required to present the original prescription at delivery for verification purposes and also permit the third-party delivery service provider to stamp the original prescription; failure to do so may result in non-delivery of the ordered Prescription Drugs. If a prescription is uploaded on behalf of another individual, the User warrants that they have the necessary authorization to act in this capacity and assume all related responsibilities

                         7.7.4. Delivery of Drugs
                         You agree to appoint an individual who shall act in the capacity of Your agent andcollect the Prescription Drugs as requested by You from Pharmacy on Your behalf("User Agent"). You accept and acknowledge that the User Agent shall be responsibleto collect the medicines ordered by You from the Pharmacy and to carry it to theaddress notified by You.  You further acknowledge that the User Agent is acting asYour authorized representative in this arrangement and their actions in collecting andtransporting the Prescription Drugs are undertaken with Your consent. ThePlatform’s/Pharmacy’s role is limited to facilitating the connection between You andthe User Agent and it assumes no responsibility for the actions of the User Agent in thecollection or delivery process.

                         7.7.5. Reuse of Prescriptions
                         ‍‍Users agree not to reuse prescriptions that have already been fulfilled. Zepto bears no responsibility for any adverse consequences resulting from the User’s self-directed use of medication and Users are advised to consult a medical professional regarding potential side effects, drug interactions and other related information before consuming any Prescription Drugs or other medications.
                         ‍‍
                         7.7.6. Drug Substitutions
                         ‍‍Orders for substitutions of prescribed medications will only be processed if the prescribing physician has expressly authorized the dispensing of an equivalent generic drug in place of the prescribed brand-name drug, if the prescription specifies only the generic salt names, or if the physician has indicated on the prescription that substitution is permitted. If neither condition is met, the Pharmacy will not process a substitution. Users acknowledge that in such instances the responsibility for substitution authorizations rests solely with the prescribing physician.

                         7.7.7. Telemedicine Consultation services and Disclaimer
                         ‍‍If the prescription uploaded by You is found to be incomplete or unavailable, Zepto may facilitate the consultation between You and TeleMedicine Consultants (as defined below) for your assistance.   Zepto does not offer medical advice or consultations on health matters. All materials accessible through the Platform, including articles, blogs, images, and other informational content, serve purely academic purposes and do not substitute for direct professional healthcare advice. Telemedicine consultations available on the Platform are offered through independent contractors("TeleMedicine Consultants")  engaged by the User solely at their discretion. The opinions and guidance provided by TeleMedicine Consultants are their own and do not represent Zepto's or Pharmacy’s views. Users are encouraged to consult in-person healthcare providers as needed to confirm any information or recommendations received from TeleMedicine Consultants

                         7.7.8. Limitations of Telemedicine Consultation services
                         Users acknowledge the inherent limitations of telemedicine consultations given that TeleMedicine Consultants cannot conduct physical examinations. Zepto and Pharmacy disclaim all liability for any loss or damage arising from reliance on TeleMedicine Consultants and urges Users to verify any digital medical advice independently. The nature of telemedicine consultations may limit the diagnostic scope, making it important for Users to seek in-person consultations. TeleMedicine Consultants may not be able to provide adequate responses without receiving further medical details and may therefore request additional information or decline queries requiring in-person examination. Any falsified or misleading information submitted by the User renders the telemedicine consultation invalid. In certain instances, technological or security failures could compromise the confidentiality of medical information, which the User agrees to bear as an assumed risk of using the service. Telemedicine Consultation does not substitute or replace Your relationship with Your physician or healthcare provider. Any information provided by the TeleMedicine Consultants should not be considered a replacement for professional medical advice, evaluation or care from Your physician or other qualified healthcare professionals.

                         7.7.9. Medical Emergencies
                         ‍‍Users experiencing medical emergencies should immediately seek professional medical assistance from their nearest healthcare provider or emergency service. Under no circumstances should Users rely solely on the Platform for urgent healthcare needs or delay essential medical care based on any information obtained through the Platform.

                         7.7.10. Prescription and Transaction Records
                         ‍‍Zepto and Pharmacy may retain records of prescriptions and transaction details as mandated by applicable regulations and for legitimate operational purposes.

                         8. Returns, Cancellations and Refunds:

                         8.1. Returns:

                         8.1.1 You may return the Product in an order, subject to the satisfaction of the following conditions:

                         8.1.1.1. wrong item being delivered other than what You had ordered in an order, or
                         8.1.1.2. Items substantially damaged or deteriorated in quality at the time of delivery. You agree that You shall give all the requisite proofs including but not limited to images of Products having issues.

                         8.1.2. You shall check the Products upon delivery and initiate exchange or return with the requisite proofs on the Platform, as available. You may also exchange or return the Product by contacting Our customer support team.

                         8.1.3. You may request exchange or return of the Products, purchased from the Sellers provided that the Products are sealed/unopened/unused and in original condition and on the same day of delivery/or as per the exchange/refund timeline suggested by Seller/ displayed on product check out page, if any. Please note, the requests for exchange or returns will not be accepted from the day following the day when Product/s were delivered to You unless there are certain categories of the Products for which higher return or exchange period is provided. You are requested to dispose off the Products for which refund has been processed. It is clarified that Your request for exchange or return of the Products shall only be processed if the relevant Seller accepts such request.

                         8.1.4. For digital products, including gift cards and vouchers, no returns or refunds are permitted. If You encounter any issues related to validity, usage restrictions, or redemption, You must contact the respective issuer. Please review the issuer or Platform’s terms and conditions which apply alongside these Terms.

                         8.2. Cancellations: You may cancel an order without charge at any time before the Seller accepts the order. You cannot cancel the order post acceptance of order. Your order may be canceled (in full or partially) for the reasons including shortage or unavailability of certain Products or force majeure events, nonavailability of services, unforeseen circumstances, delivery-related issues or if there are concerns regarding fraudulent activity or non-compliance with these Terms. In case of acceptance of cancellation of any order, You will not be charged for such cancellations and You will receive a refund for any payment already made, as early as practically possible.

                         8.3. Refunds: Please be informed that when You opt to return the Products, upon verification of the Products and the documents relating thereto, the refund amount for such Products which are eligible for return as per these Terms, will be processed within a period of seven (7) business days from the date of verifying and confirming the refund request. Your refund will be processed only when the conditions as may be stipulated by Us are fulfilled. The refund amount will be credited to the source account. You acknowledge that after initiation of refund, it may take additional time for Your refund to reflect in Your account which is subject to Your financial institution or payment gateway service provider terms and conditions. Provided that refunds, if any, for Products purchased on cash on delivery basis may also be refunded by way of coupon/vouchers which will have expiry period. Users may opt-in for a coupon/voucher refund for online payments as well if provided to them.

                         The Terms for acceptance of returns, cancellation and refunds shall be subject to reasonable additional conditions and shall be communicated to the User, from time to time.

                         9. User care:

                         9.1. The User acknowledges and agrees that Zepto shall not be held liable for:

                         9.1.1. The services or Products offered by Sellers, including but not limited to Café Orders that may or may not meet Your preferences or requirements.
                         9.1.2. The quality of the Seller’s services or Products, or any issues arising from services provided by third-party delivery service providers that do not meet User expectations, potentially resulting in loss, harm, or damage.
                         9.1.3. The nonavailability Products or services.
                         9.1.4. Incorrect Orders fulfilled by the Seller, or any liability associated with Products sold by the Seller.

                         9.2. The information about Products and the associated catalogue, including pricing, displayed on the Platform is provided by the Sellers. Zepto cannot be held liable for any changes, correctness or errors or omissions of the information, or unavailability of these Products and services.
                         ‍‍
                         9.3. Zepto is not and cannot be a party to any transaction between You and Sellers or have any control, involvement or influence over the Products purchased/services availed by You from such Sellers. You acknowledge and agree that Zepto shall not, at any time, have any ownership, control, and/or title to any Product(s), which is subject to a bipartite sale and purchase transaction between You and the relevant Seller. Zepto does not provide any warranty or guarantee with respect to the Products and/or services offered for sale on the Platform and disclaims any liability with respect to the manufacturing defects, quality, taste, performance of the Products/services sold. All commercial and contractual arrangements regarding the Products and  services offered for sale are solely between Users and Sellers. These arrangements encompass various terms, including but not limited to pricing, product and service quality, applicable taxes, delivery and other fees, payment conditions, warranties (if any), and after-sales support. Zepto may, however, provide support services to Sellers in respect to Order fulfillment, mode of payment, payment collection, customer support, technology and other ancillary services, pursuant to independent contracts executed between Zepto and the Sellers.

                         9.4. Zepto does not guarantee or endorse the specifics of any Seller, including aspects like legal ownership, creditworthiness, or identity. We recommend that You conduct Your own due diligence to verify the legitimacy of any Seller You choose to engage with on the Platform and exercise Your discretion. All offers from Sellers and third parties are governed by their respective terms and conditions and Zepto assumes no responsibility for these offers.

                         9.5. You agree and understand that the Product images are representation of the Product and not actual image of the Product sold to You and You shall read the physical product label for the calorific and nutrition value, using instructions, batch, manufacture date, use by date/shelf life, content, weight, manufacturer and the customer support details, as may be relevant, before consumption of the Products including but not limited to Café orders. WHILE EVERY REASONABLE EFFORT IS MADE TO MAINTAIN ACCURACY OF INFORMATION ON THE PLATFORM, ACTUAL PRODUCT PACKAGING, MAY CONTAIN MORE AND/OR DIFFERENT INFORMATION THAN WHAT IS SHOWN ON THE PLATFORM. IT IS RECOMMENDED TO REFER THE INFORMATION PRESENTED ON THE ACTUAL PRODUCT PACKAGING.

                         9.6. Zepto reserves its right to refuse to process transactions by Users with a prior history of questionable transactions including without limitation breach of any agreements by User with Zepto or breach/violation of any law or any charges imposed by bank or breach of any policy without giving any reasons. Zepto may do such checks as it deems fit before approving the User's order for security or other reasons at the discretion of Zepto. As a result of such checks, if Zepto is not satisfied with the credibility of the User or genuineness of the transaction, it will have the right to reject the order/s placed by such Users or disable their access to the Platform. Transactions on the Platform may be delayed, suspended, or canceled at Zepto's sole discretion for any reason (to maintain the integrity, security, and equitable usage of the Platform), including but not limited to suspicious activities, concerns regarding the User's authenticity or behavior, unusually high transaction volumes, safety concerns, or to ensure the fair use of the Platform.

                         ‍‍Beware of fraud:

                         9.7. Please do not share Your debit/credit card number, CVV number, OTP, UPI/ATM pin and other sensitive information with anyone claiming to be a Zepto representative. Zepto or its authorised representatives will NEVER ask You to share the aforesaid details. Beware of fraudsters and please report incidents immediately to Your bank, the nearest police station and at https://cybercrime.gov.in/.

                         9.8. For assistance on a Zepto order or refund related issues, click on the ‘Get Help’ section on the App.

                         9.9. Please exercise caution to verify the portals/website links claiming to be Zepto or a lookalike or a payment link shared over social media or a social messaging apps claiming to be Zepto discounts or offers and proactive calls from unauthorised numbers or unauthorized social media accounts requesting for personal/financial information.

                         10. Use of Platform

                         10.1. Subject to compliance with the Terms, Zepto hereby grants You a personal, non-exclusive, non- transferable, limited, revocable privilege to access and use the Platform. You agree to use the Platform only: (a) for purposes that are permitted by the Terms; (b) in accordance with any applicable law, regulation or generally accepted practices or guidelines; and (c) for availing the services through the Platform. You agree not to engage in activities that may adversely affect the use of the Platform by Zepto and/or other Users.

                         10.2. You agree that the Platform or any portion of the Platform shall not be reproduced, duplicated, copied, sold, resold or otherwise exploited for commercial purposes.

                         10.3. You agree to not frame or utilise the framing techniques to enclose any trademark, logo or any other proprietorship information of the Platform.

                         10.4. You agree not to access (or attempt to access) the Platform by any means other than through the interface that is provided by Zepto. You shall not use any deep- link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Platform.

                         10.5. Further, You undertake not to host, display, upload, modify, publish, transmit, store, update or share any information that:

                         10.5.1. belongs to another person and to which the User does not have any right;
                         10.5.2. is defamatory, obscene, pornographic, paedophilic, invasive of another's privacy,including bodily privacy, insulting, or harassing on the basis of gender, libelous,racially, or ethnically objectionable, relating or encouraging money laundering orgambling, or otherwise inconsistent with or contrary to the laws in force;
                         10.5.3. is harmful to child;
                         10.5.4. infringes any patent, trademark, copyright, or other proprietary rights;
                         10.5.5. violates any law for the time being in force;
                         10.5.6. impersonates another person;
                         10.5.7. threatens the unity, integrity, defence, security or sovereignty of India, friendlyrelations with foreign States, or public order, or causes incitement to the commission ofany cognisable offence or prevents investigation of any offence or is insulting othernation;
                         10.5.8. contains software virus or any other computer code, file or program designed tointerrupt, destroy, or limit the functionality of any computer resource;
                         10.5.9. is patently false and untrue, and is written or published in any form, with the intent tomislead or harass a person, entity, or agency for financial gain or to cause any injury toany person;
                         10.5.10. disrupt or interfere with the security of, or otherwise cause harm to, the Platform,systems resources, accounts, passwords, servers, or networks connected to oraccessible through the Platform or any affiliated or linked sites;
                         10.5.11. violate the Terms contained herein or elsewhere; and
                         10.5.12. reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce,publish, license, create derivative works from, transfer, or sell any information orsoftware obtained from the Platform.

                         10.6. You shall solely be responsible for maintaining the necessary computer equipment, gadgets and internet connections that may be required to access, use, and transact on the Platform.

                         10.7. You understand and acknowledge that by using the Platform or any of the services, You may encounter Content that may be deemed by some Users to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Platform and any services at Your sole risk and that to the fullest extent permitted under applicable law. Zepto shall have no liability to You for Content that may be deemed offensive, indecent, or objectionable to You.

                         11. Intellectual Property Rights

                         11.1. The Platform and the processes, and their selection and arrangement, including but not limited to, texts, videos, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork and computer code (and any combinations thereof) (collectively, the “Content”)  on the Platform is either owned by or licensed by  Zepto  and the design, structure, selection, coordination, expression, look and feel and arrangement of such Content is protected by copyright, patent and trademark laws, and various other intellectual property rights.

                         11.2. The trademarks, logos and service marks displayed on the Platform (“Marks”) are the licensed property of Zepto or owned by third parties. You are not permitted to use the Marks without the prior consent of Zepto or the relevant third party (which is the owner of the Marks) respectively. Access or use of the Platform does not authorise any party to use trademarks, logo, or any other mark in any manner.

                         11.3. Zepto disclaims to hold any right, title, or interest in and to the intellectual property rights arising out of or associated with the Products and services sold by the Sellers on the Platform.

                         11.4. References on the Platform of any name, mark, services or products of third parties has been provided for Your convenience, and in no way constitutes an endorsement, sponsorship or recommendation, whether express or implied.

                         11.5. Where Platform contains links to other sites provided by third parties, these links are provided for information only. We have no visibility or control over the contents on or available through those sites and You acknowledge and agree that We have no liability for any such content.

                         11.6. Zepto word mark and variances together with device marks displayed on the Platform shall be the licensed property of Us and any use, unless expressly permitted in writing shall amount to infringement and You shall hereby agree and undertake that You recognise Our intellectual property rights and upon acquiring knowledge of any infringement by any third parties, shall report to Us at legal@zeptonow.com

                         12. Disclaimer of Warranties & Liability

                         12.1. You expressly understand and agree that, to the maximum extent permitted by applicable law:

                         12.1.1. The Platform and other Content are provided by Zepto on an “as is” basis without warranty of any kind, express, implied, statutory, or otherwise, including the implied warranties of title, non-infringement, merchantability, or fitness for a particular purpose. Without limiting the foregoing, Zepto makes no warranty that the Platform or services  will meet Your requirements, or Your use of the Platform will be uninterrupted, timely, secure, or error-free. No advice or information, whether oral or written, obtained by You from Zepto shall create any warranty not expressly stated in the Terms.

                         12.1.2. Zepto will not be liable for any loss that You may incur as a consequence of unauthorized use of Your Account or Account information in connection with the Platform either with or without Your knowledge.

                         12.1.3. Zepto shall not nor is it obligated to mediate or resolve any disputes or disagreements that may arise between You and the Sellers. Zepto does not endorse either implicitly or explicitly, any sale or purchase of Products or services listed on the Platform. However, upon receiving a written request from You following the purchase of any Products and/or services on the Platform, Zepto may provide additional information about the Sellers involved in the transaction as available to facilitate direct communication between You and Sellers for the purpose of dispute resolution.

                         12.1.4. Zepto has endeavored to ensure that all the information on the Platform is accurate, but Zepto neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information regarding the services or otherwise. Zepto shall not be responsible for the delay or inability to use the Platform or related functionalities, the provision of or failure to provide functionalities, or for any information, software, functionalities, and related graphics obtained through the Platform, or otherwise arising out of the use of the Platform, whether based on contract, tort, negligence, strict liability or otherwise. Further,  Zepto  shall not be held responsible for non-availability of the Platform during periodic maintenance operations or any unplanned suspension of access to the Platform that may occur due to technical reasons or for any reasons beyond Zepto’s reasonable control.

                         12.1.5. Colours of the Products displayed on the Platform are as accurately as possible. However, the actual colours of the Products You see will depend on Your monitor or device, and We/Sellers do not provide any guarantee in respect of such display and will not be responsible or liable for the same

                         12.2. Zepto makes no representation that the Content on the Platform is appropriate to be used or accessed outside the Republic of India. Any Users who use or access the Platform from outside the Republic of India, do so at their own risk and are responsible for compliance with the laws of such jurisdiction and also consent to Zepto for use of their personal and other information only for the purpose of provision of services. By visiting the Platform or providing Your information, You expressly agree to be bound by these Terms and Our Privacy Notice and also agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If You do not agree please do not use or access our Platform.

                         12.3. The Terms do not constitute, nor may the Terms be used for or in connection with any promotional activities or solicitation by anyone in any jurisdiction in which such promotional activities or solicitation are not authorized or to any person to whom it is unlawful to promote or solicit.

                         12.4. Prices for any Product(s) displayed on the Platform may be inaccurate due to technical issues, typographical errors, or incorrect information provided by the Seller. In such cases, the Seller reserves the right to cancel the User’s Order(s).

                         12.5. Zepto accepts no responsibility for any breaches of applicable laws, including those governing the Products and services offered by Sellers or third-party delivery service providers or by payment gateway service providers.

                         12.6. You acknowledge that third-party services are available on the Platform, and We may partner with certain third parties to facilitate such services. However, You agree that We make no representations or warranties regarding these third-party services or products and will not be liable for any outcomes, including injury, impairment, or death, resulting from their use. You hereby waive any rights or claims You may have against Us in relation to third-party services.

                         13. Indemnification and Limitation of Liability

                         13.1. You agree to indemnify, defend and hold harmless Zepto, Sellers, service providers, its officers, directors, consultants, agents, representatives and employees; and its third party partners (“Indemnitees”) from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including reasonable legal fees) asserted against or incurred by the Indemnitees that arise out of, result from, or may be payable by virtue of, any breach or non- performance of any representation, warranty, covenant or agreement made or obligation to be performed by You pursuant to these Terms and/or the Privacy Notice. Further, You agree to hold the Indemnitees harmless against any claims made by any third party due to, or arising out of, or in connection with, Your use of the Platform, any misrepresentation with respect to the data or information provided by You, Your violation of the Terms and/or the Privacy Notice, Your violation of applicable laws, or Your violation of any rights of third parties, including any intellectual property rights.

                         13.2. In no event shall Zepto, its Sellers, its service providers and its directors, officers, partners, consultants, agents, and employees and its partners, be liable to You or any third party for any special, incidental, indirect, consequential, or punitive damages whatsoever, arising out of or in connection with Your use of or access to the Platform or Content on the Platform. Notwithstanding any provisions herein, Zepto, Sellers, service providers’ maximum total liability shall not exceed the amount paid by the User for the purchase of the Product and/or services under the specific order to which the liability relates.

                         13.3. The limitations and exclusions in this Section apply to the maximum extent permitted by applicable laws.

                         14. Violation of these Terms

                         14.1. You agree that any violation by You of these Terms will likely cause irreparable harm to Zepto,for which monetary damages would be inadequate and You consent to Zepto obtaining anyinjunctive or equitable relief that they deem necessary or appropriate in such circumstances.These remedies are in addition to any other remedies that Zepto may have at law or in equity.

                         15. Suspension and Termination

                         15.1. The Terms will continue to apply until terminated by either You or Zepto as set forth below. If You object to the Terms or are dissatisfied with the Platform, You may (i) close Your Account on the Platform; and/or (ii) stop accessing the Platform.

                         15.2. Zepto may disable Your access or block Your future access to the Platform or suspend or terminate Your Account if it believes, in its sole and absolute discretion, that You have violated any term of these Terms or the Privacy Notice or in any way otherwise acted unethically. Notwithstanding contained herein, all terms which by their nature are intended to survive such termination, will survive indefinitely unless and until Zepto chooses to terminate them.

                         15.3. Any such termination shall not cancel Your obligation to pay for a Product or a service purchased on the Platform, or any other obligation which has accrued, or is unfulfilled and relates to the period, prior to termination.

                         15.4. You shall be liable to pay any fees or charges, if applicable in respect of the services until the date of termination by either party whatsoever.

                         16. Governing Law and Jurisdiction

                         16.1. These Terms shall be governed by and constructed in accordance with the laws of India without reference to conflict of laws principles and disputes arising in relation hereto shall be subject to the exclusive jurisdiction of courts at Bengaluru, India.

                         17. Grievance Redressal Mechanism

                         17.1.1. For any order related issue, You may first reach out to Us via chat support on the Appfor real time basis resolution.
                         17.1.2. You may also write to Us at support@zeptonow.com and We will strive to resolveYour order related issues within the timelines prescribed under applicable laws.
                         17.1.3. If You still have any grievances, or complaints or concerns with respect to the Platformor order or are not satisfied with the resolution, the Content, or the services, You cancontact the designated Grievance cum Nodal Officer of Zepto as per the below details:

                         Mr. Zubair Shaikh
                         Zepto Marketplace Private Limited
                         Address: Ground Floor, Sy. No.32/5, BBMP Khata No. 224/215, Rupena Agrahara,Hosur Rd, Bommanahalli, Bommanahalli, Bengaluru Karnataka, India, 560068
                         Phone: 8976517761
                         Email: grievances@zeptonow.com
                         Time: Mon – Sat (9:00 – 18:00)The aforementioned details of the Grievance cum Nodal Officer is provided incompliance of (1) Information Technology Act, 2000 and rules made there under, and(2) Consumer Protection (E-Commerce) Rules 2020, as amended time to time

                         17.2. The Grievance Officer of Zepto shall endeavour to acknowledge the User grievances, or complaints or concerns with respect to the Platform, the Content, or the services, within 48 hours of receipt of the same and shall endeavour to redresses the same at the earliest and in no event later than 30 (thirty) days of receipt of such request. By lodging a complaint or grievance, You agree to provide complete support to the Grievance Officer and such reasonable information as may be sought by them from You.

                         18. Notice of Infringement and Take Down Policy 

                         18.1. Zepto’s Take Down Policy enables intellectual property owners to quickly report and remove infringing listings from the Platform.

                         18.2. Intellectual property owners can report potentially infringing Products or listings by submitting a Notice of Infringement containing all the details as mentioned below. Zepto cannot independently verify that Sellers have the rights to sell or distribute their Products or services but is fully committed to protecting intellectual property rights.

                         18.3. Steps to report a listing:
                         ‍‍If You have a sincere belief that a Seller on Our Platform is infringing Your intellectual property rights, please follow the below steps. We request You to provide the following information and email it to legal@zeptonow.com. The email should include:

                         18.3.1. Identification or description of the copyrighted work/ trademark that has been infringed along with registration/application details and images.
                         18.3.2. Your contact information.
                         18.3.3. An undertaking from You that

                         a. You have a good faith belief that the use of the material complained of is not authorized by the trademark or copyright or intellectual property owner, its agent, or the law.
                         b. The information in the notice is accurate and that You are the trademark or copyright or intellectual property owner or authorized to act on the trademark or copyright or intellectual property owner's behalf.

                         18.3.4. Such other information that You think is important for supporting Your claim.

                         18.4. Zepto’s actions 

                         Upon receiving a duly completed notice with the necessary documentation as described above, and after confirming the authenticity of the claim, Zepto may take steps to remove or disable access to the alleged infringing content provided by third parties. Zepto may also inform the respective Seller who submitted the content in question, providing them with a copy of the infringement notice. We reserve the right to undertake any further actions as permitted by the applicable laws in effect at the time of notification.

                         19. Communications

                         19.1. You hereby expressly agree to receive communications by way of SMS, telephone or VOIP calls, messaging app like WhatsApp on the registered mobile phone number /or electronic communications like e-mails from Zepto and other third parties duly authorised by Zepto. You hereby expressly consent to the monitoring and recording, by Zepto and/or any third party of any and all communications between You and  Zepto  or its agents, employees, consultants, contractors, or representatives of Zepto or of their authorised partners, and such monitoring or recording waives any further notice or consent requirement under the applicable laws.

                         19.2. You can unsubscribe or opt-out from receiving promotional communications from Zepto. In which case, Zepto will only send communications solely required for the purposes of availing the services by You.

                         20. General Provisions

                         20.1. Notice: All notices from Zepto will be served by email to Your registered email address or by messaging app on the registered mobile phone number or by general notification on the Platform.

                         20.2. Assignment: You cannot assign or otherwise transfer any rights granted hereunder to any third party. Zepto’s rights and obligations under the Terms are freely transferable by Zepto to its successor or to its affiliates or or any third party without the requirement of seeking Your consent.

                         20.3. Severability: If, for any reason any provision of the Terms, or any portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties as reflected by that provision, and the remainder of the Terms shall continue in full force and effect.

                         20.4. Force Majeure: Zepto, its Sellers, its service providers shall not be liable to You for its failure to perform or for delay in providing You access to Your Account or to the Platform or any services thereof, to the extent such failure or delay results from causes beyond its reasonable control, including, without limitation, acts of God, fires, explosions, wars or other hostilities, insurrections, revolutions, strikes, labour unrest, earthquakes, floods, riots, excessive rains, pandemic, epidemics or regulatory or quarantine restrictions, unforeseeable governmental restrictions or controls or a failure by a third party hosting provider or internet service provider or on account of any change or defect in the software and/or hardware of Your computer system.

                         21. Advertisements

                         21.1. As part of the services provided by Us, We may facilitate and allow third party advertisers (“Third Party Advertisers”) to place advertisements on the Platform. You understand that any content put out by Third Party Advertisers is not edited, reviewed or otherwise endorsed by Zepto and We disclaim to the fullest extent permitted by law any liability for the content published by the Third Party Advertisers. It is solely the responsibility of the Third Party Advertisers submitting material to the Platform to ensure compliance with all relevant laws. Any interactions or transactions You undertake with Third Party Advertisers found on the Platform including payments, delivery, and terms or representations related to their goods or services are strictly between You and the Third Party Advertiser. Zepto bears no liability for errors, omissions, or inaccuracies in advertising content or for any losses or damages arising from Your dealings with these advertisers or their presence on the Platform.

                         21.2. To the extent You are a Third Party Advertiser You understand that in addition to these Terms You will also be required to agree to Zepto’s policies and other contractual agreements that You will need to execute for placing Your advertisement. As a general principle the content in the advertisements should not be misleading or in violation of applicable law or guidelines issued by the Advertising Standards Council of India or any other self-regulating body. You also acknowledge that  We have the sole right at  Our discretion to remove any Third Party Advertisement or require You to prove factual substantiation if We are of the view that it is in violation of applicable law or any self-regulating industry body guidelines or is otherwise misleading.

                         21.3. If You are of the view that the content of a Third Party Advertiser is inappropriate or in violation of applicable law, please write to Us at the email address provided above.

                         21.4. For any charitable campaign information shared with Users or displayed on the Platform, where donations may be made through third-party sites or accounts, Zepto may not be involved in fund collection or use. Zepto bears no responsibility for the accuracy or legality of campaign information, which is provided solely for reference. Users are encouraged to verify details independently before taking action.

                         22. Severability:

                         22.1. If any part of these Terms is found to be invalid, void, or unenforceable, that portion will be treated as separable, and the remaining provisions will continue in full force and effect.

                         23. Amendments:

                         23.1. We may modify these Terms periodically, without prior notice, to include updates, revisions, additions, or new policies affecting Your use of the services. Such changes will be posted on the Platform and take effect immediately upon posting. We encourage You to review these Terms on the Platform regularly for any updates. By continuing to use the services and/or the Platform, You agree to accept any revised Terms.

                         24. Transition:

                         24.1. THE PLATFORM IS UNDERGOING A TRANSITION WHERE THE PLATFORM WILL BE OPERATED BY ZEPTO MARKETPLACE PRIVATE LIMITED FROM THE DATE WHICH SHALL BE COMMUNICATED TO YOU. PURSUANT TO THE TRANSITION THE EXISTING USER OF ZEPTO SERVICES HERE BY CONSENT TO THE FOLLOWING:

                         24.1.1. FOR THE TRANSFER OF UNUSED FUNDS HELD IN YOUR WALLET BALANCE TO A ZEPTO GIFT CARD.
                         24.1.2. FOR THE TRANSFER OF YOUR PAYMENT RELATED INFORMATION AND INSTRUMENTS AS AVAILABLE WITH THE SERVICE PROVIDER OF ZEPTO TO ENSURE SEAMLESS EXPERIENCE FOR USERS POST TRANSITION.

                         23. Entire agreement:

                         23.1. This document, including the Privacy Notice and any policies that Zepto may introduce from time to time, represents the entire understanding between You and Zepto. It establishes the Terms for Your access to and use of the services and Platform superseding any earlier arrangements related to such access or use.

                         Zepto Super Saver

                         ©️ 2025 Zepto, All rights reserved.

                         Zepto Logo
                         Home
                         Delivery Areas
                         Careers
                         Customer Support
                         Press
                         Mojo - Our Blog
                         Instagram
                         Facebook
                         Twitter
                         LinkedIn
                         .
                         ©️ Zepto Marketplace Private Limited
                         Privacy Policy
                         Terms of Use
                         Responsible Disclosure Policy
                         Made in Webflow
                         """)
                    .foregroundColor(.white)
                }
                .padding()
                .padding(.top,50)
            }
            .background(LinearGradient(
                gradient: Gradient(colors: [Color.purple.opacity(0.9), Color.black]),
                startPoint: .top,
                endPoint: .bottom
            ))
            .edgesIgnoringSafeArea(.all)
        }
        .navigationBarBackButtonHidden(true)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button(action: {
                        presentationMode.wrappedValue.dismiss()
                    }) {
                        HStack {
                            Image(systemName: "chevron.left")
                                .foregroundColor(.black)
//                            Spacer()
//                            Text("SuggestProducts")
//                                .foregroundColor(.black)
                               
//                            Spacer()
                        }
                    }
                }
            }

    }
        
        
}


#Preview {
    TermsOfUseView()
}
